forgot_password_question: Write your date of birth followed by any 3 digits. (E.g. yyyyMMddxxx 20050203523)

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1.0
    
# ACTUATOR CONFIGS
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - include= *

spring:
  data:
    mongodb:
#      host: ${DB_HOST}
#      port: ${DB_PORT}
#      authentication-database: admin
#      username: ${DB_USR}
#      password: ${DB_PWD}
#      database: ${DB_NAME}
      uri: mongodb://subham000:${DB_PWD}@subham-tweetap-db-cluster.cluster-cs0jdd1w03hc.ap-south-1.docdb.amazonaws.com:27017/tweetapp-db?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      
   
  
swagger_api_doc:
  group_name: Tweet App public API
  title: Tweet API
  api_regex: /api/v1.0.*
  description: Tweet Application API reference for UI/UX developer
  contact_name: Subham Santra
  contact_url:
  contact_email: subham.santra@cognizant.com
  license: FSE1 Acreditation license
  license_url: subham_santra@dummy_license.com
  version: v1.0
  
jwt.lifetime: 3600000 # 60 minute
#jwt.lifetime: 60000 # 1 minute
#jwt.lifetime: 3000 # 3 second
#jwt.lifetime: 3000 # 3 second

admin:
  email: ${ADMIN_NAME:subham.santra@cognizant.com}
  password: ${ADMIN_PASSWORD:changeit}
  
management:
  endpoint:    prometheus:      enabled: true
      
  endpoints:
    web:
      exposure:
        include:
          - '*'
        exclude:
          - beans
          - env
          - shutdown
