forgot_password_question: Write your date of birth followed by any 3 digits. (E.g. yyyyMMddxxx 20050203523)

server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /api/v1.0
    
# ACTUATOR CONFIGS
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - include= *

spring:
  data:
    mongodb:
      uri: ${NOSQL_DB_PROTO:mongodb}:${CRED_DETAILS:}//${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:test}?${DB_CONN_PARAMS:}
#      uri: mongodb://ec2-3-111-37-99.ap-south-1.compute.amazonaws.com:27017/tweet-app-db
  
swagger_api_doc:
  group_name: Tweet App public API
  title: Tweet API
  api_regex: /api/v1.0.*
  description: Tweet Application API reference for UI/UX developer
  contact_name: Subham Santra
  contact_url:
  contact_email: subham.santra@cognizant.com
  license: FSE1 Acreditation license
  license_url: subham_santra@dummy_license.com
  version: v1.0
  
jwt.lifetime: 3600000 # 60 minute
#jwt.lifetime: 60000 # 1 minute
#jwt.lifetime: 3000 # 3 second
#jwt.lifetime: 3000 # 3 second

admin:
  email: ${ADMIN_NAME:subham.santra@cognizant.com}
  password: ${ADMIN_PASSWORD:changeit}
  
management:
  endpoint:    prometheus:      enabled: true
      
  endpoints:
    web:
      exposure:
        include:
          - '*'
        exclude:
          - beans
          - env
          - shutdown
